package deloitte.fin.gl.coa.module.common.serviceinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 12:52:35 IST 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/deloitte/fin/gl/coa/module/common/",
    name="COAAMService", wsdlLocation="deloitte/fin/gl/coa/module/common/serviceinterface/COAAMService.wsdl")
@SDODatabinding(schemaLocation="deloitte/fin/gl/coa/module/common/serviceinterface/COAAMService.xsd")
public interface COAAMService {

    public static final String NAME = "{/deloitte/fin/gl/coa/module/common/}COAAMService";

    /**
     * Exported method getTargetString from COAAM.
     */
    @WebMethod(action="/deloitte/fin/gl/coa/module/common/getTargetString",
        operationName="getTargetString")
    @RequestWrapper(targetNamespace="/deloitte/fin/gl/coa/module/common/types/",
        localName="getTargetString")
    @ResponseWrapper(targetNamespace="/deloitte/fin/gl/coa/module/common/types/",
        localName="getTargetStringResponse")
    @WebResult(name="result")
    String getTargetString(@WebParam(mode = WebParam.Mode.IN, name="pSourceSystem")
        String pSourceSystem, @WebParam(mode = WebParam.Mode.IN, name="pTargetSystem")
        String pTargetSystem, @WebParam(mode = WebParam.Mode.IN, name="pSourceString")
        String pSourceString) throws ServiceException;
}
