package deloitte.fin.gl.coa.view;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 17:48:17 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class COAMappingRulesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RuleId {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getRuleId();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setRuleId((Number)value);
            }
        }
        ,
        RuleName {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getRuleName();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setRuleName((String)value);
            }
        }
        ,
        Description {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        SourceSystem {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getSourceSystem();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setSourceSystem((String)value);
            }
        }
        ,
        TargetSystem {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getTargetSystem();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setTargetSystem((String)value);
            }
        }
        ,
        StartDate {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        EnabledFlag {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getEnabledFlag();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setEnabledFlag((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        COASegmentMappingsVO {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCOASegmentMappingsVO();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COASegmentValuesVO {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCOASegmentValuesVO();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COATargetSystemLOVVO1 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCOATargetSystemLOVVO1();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COAMappingRuleLOVVO1 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCOAMappingRuleLOVVO1();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COASourceSystemLOVVO1 {
            public Object get(COAMappingRulesVORowImpl obj) {
                return obj.getCOASourceSystemLOVVO1();
            }

            public void put(COAMappingRulesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(COAMappingRulesVORowImpl object);

        public abstract void put(COAMappingRulesVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RULEID = AttributesEnum.RuleId.index();
    public static final int RULENAME = AttributesEnum.RuleName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SOURCESYSTEM = AttributesEnum.SourceSystem.index();
    public static final int TARGETSYSTEM = AttributesEnum.TargetSystem.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ENABLEDFLAG = AttributesEnum.EnabledFlag.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int COASEGMENTMAPPINGSVO = AttributesEnum.COASegmentMappingsVO.index();
    public static final int COASEGMENTVALUESVO = AttributesEnum.COASegmentValuesVO.index();
    public static final int COATARGETSYSTEMLOVVO1 = AttributesEnum.COATargetSystemLOVVO1.index();
    public static final int COAMAPPINGRULELOVVO1 = AttributesEnum.COAMappingRuleLOVVO1.index();
    public static final int COASOURCESYSTEMLOVVO1 = AttributesEnum.COASourceSystemLOVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public COAMappingRulesVORowImpl() {
    }

    /**
     * Gets COAMappingRulesEO entity object.
     * @return the COAMappingRulesEO
     */
    public EntityImpl getCOAMappingRulesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for RULE_ID using the alias name RuleId.
     * @return the RULE_ID
     */
    public Number getRuleId() {
        return (Number)getAttributeInternal(RULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ID using the alias name RuleId.
     * @param value value to set the RULE_ID
     */
    public void setRuleId(Number value) {
        setAttributeInternal(RULEID, value);
    }

    /**
     * Gets the attribute value for RULE_NAME using the alias name RuleName.
     * @return the RULE_NAME
     */
    public String getRuleName() {
        return (String) getAttributeInternal(RULENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_NAME using the alias name RuleName.
     * @param value value to set the RULE_NAME
     */
    public void setRuleName(String value) {
        setAttributeInternal(RULENAME, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SOURCE_SYSTEM using the alias name SourceSystem.
     * @return the SOURCE_SYSTEM
     */
    public String getSourceSystem() {
        return (String) getAttributeInternal(SOURCESYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_SYSTEM using the alias name SourceSystem.
     * @param value value to set the SOURCE_SYSTEM
     */
    public void setSourceSystem(String value) {
        setAttributeInternal(SOURCESYSTEM, value);
    }

    /**
     * Gets the attribute value for TARGET_SYSTEM using the alias name TargetSystem.
     * @return the TARGET_SYSTEM
     */
    public String getTargetSystem() {
        return (String) getAttributeInternal(TARGETSYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_SYSTEM using the alias name TargetSystem.
     * @param value value to set the TARGET_SYSTEM
     */
    public void setTargetSystem(String value) {
        setAttributeInternal(TARGETSYSTEM, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for ENABLED_FLAG using the alias name EnabledFlag.
     * @return the ENABLED_FLAG
     */
    public String getEnabledFlag() {
        return (String) getAttributeInternal(ENABLEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ENABLED_FLAG using the alias name EnabledFlag.
     * @param value value to set the ENABLED_FLAG
     */
    public void setEnabledFlag(String value) {
        setAttributeInternal(ENABLEDFLAG, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link COASegmentMappingsVO.
     */
    public RowIterator getCOASegmentMappingsVO() {
        return (RowIterator)getAttributeInternal(COASEGMENTMAPPINGSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link COASegmentValuesVO.
     */
    public RowIterator getCOASegmentValuesVO() {
        return (RowIterator)getAttributeInternal(COASEGMENTVALUESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COATargetSystemLOVVO1.
     */
    public RowSet getCOATargetSystemLOVVO1() {
        return (RowSet)getAttributeInternal(COATARGETSYSTEMLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAMappingRuleLOVVO1.
     */
    public RowSet getCOAMappingRuleLOVVO1() {
        return (RowSet)getAttributeInternal(COAMAPPINGRULELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COASourceSystemLOVVO1.
     */
    public RowSet getCOASourceSystemLOVVO1() {
        return (RowSet)getAttributeInternal(COASOURCESYSTEMLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
