package deloitte.fin.gl.coa.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 17:48:17 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class COAMappingRulesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public COAMappingRulesVOImpl() {
    }
}
