package deloitte.fin.gl.coa.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 12 16:45:27 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CoaStringValuesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CoaStringValuesVOImpl() {
    }

    /**
     * Returns the bind variable value for pSourceSystem.
     * @return bind variable value for pSourceSystem
     */
    public String getpSourceSystem() {
        return (String)getNamedWhereClauseParam("pSourceSystem");
    }

    /**
     * Sets <code>value</code> for bind variable pSourceSystem.
     * @param value value to bind as pSourceSystem
     */
    public void setpSourceSystem(String value) {
        setNamedWhereClauseParam("pSourceSystem", value);
    }

    /**
     * Returns the variable value for pSourceValue.
     * @return variable value for pSourceValue
     */
    public String getpSourceValue() {
        return (String)ensureVariableManager().getVariableValue("pSourceValue");
    }

    /**
     * Sets <code>value</code> for variable pSourceValue.
     * @param value value to bind as pSourceValue
     */
    public void setpSourceValue(String value) {
        ensureVariableManager().setVariableValue("pSourceValue", value);
    }

    /**
     * Returns the variable value for pTargetSystem.
     * @return variable value for pTargetSystem
     */
    public String getpTargetSystem() {
        return (String)ensureVariableManager().getVariableValue("pTargetSystem");
    }

    /**
     * Sets <code>value</code> for variable pTargetSystem.
     * @param value value to bind as pTargetSystem
     */
    public void setpTargetSystem(String value) {
        ensureVariableManager().setVariableValue("pTargetSystem", value);
    }

    /**
     * Returns the bind variable value for pTargetValue.
     * @return bind variable value for pTargetValue
     */
    public String getpTargetValue() {
        return (String)getNamedWhereClauseParam("pTargetValue");
    }

    /**
     * Sets <code>value</code> for bind variable pTargetValue.
     * @param value value to bind as pTargetValue
     */
    public void setpTargetValue(String value) {
        setNamedWhereClauseParam("pTargetValue", value);
    }
}
