package deloitte.fin.gl.coa.view;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 23:56:37 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class COASearchVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SourceValue {
            public Object get(COASearchVORowImpl obj) {
                return obj.getSourceValue();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setSourceValue((String)value);
            }
        }
        ,
        ValueId {
            public Object get(COASearchVORowImpl obj) {
                return obj.getValueId();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setValueId((Number)value);
            }
        }
        ,
        TargetValue {
            public Object get(COASearchVORowImpl obj) {
                return obj.getTargetValue();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setTargetValue((String)value);
            }
        }
        ,
        EnabledFlag {
            public Object get(COASearchVORowImpl obj) {
                return obj.getEnabledFlag();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setEnabledFlag((String)value);
            }
        }
        ,
        EndDate {
            public Object get(COASearchVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        StartDate {
            public Object get(COASearchVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        RuleName {
            public Object get(COASearchVORowImpl obj) {
                return obj.getRuleName();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setRuleName((String)value);
            }
        }
        ,
        SourceSystem {
            public Object get(COASearchVORowImpl obj) {
                return obj.getSourceSystem();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setSourceSystem((String)value);
            }
        }
        ,
        TargetSystem {
            public Object get(COASearchVORowImpl obj) {
                return obj.getTargetSystem();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setTargetSystem((String)value);
            }
        }
        ,
        Description {
            public Object get(COASearchVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        RuleId {
            public Object get(COASearchVORowImpl obj) {
                return obj.getRuleId();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setRuleId((Number)value);
            }
        }
        ,
        RuleId1 {
            public Object get(COASearchVORowImpl obj) {
                return obj.getRuleId1();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setRuleId1((Number)value);
            }
        }
        ,
        RuleId2 {
            public Object get(COASearchVORowImpl obj) {
                return obj.getRuleId2();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setRuleId2((BigDecimal)value);
            }
        }
        ,
        SourceSegment {
            public Object get(COASearchVORowImpl obj) {
                return obj.getSourceSegment();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setSourceSegment((String)value);
            }
        }
        ,
        TargetSegment {
            public Object get(COASearchVORowImpl obj) {
                return obj.getTargetSegment();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setTargetSegment((String)value);
            }
        }
        ,
        EnableFlagBoolean {
            public Object get(COASearchVORowImpl obj) {
                return obj.getEnableFlagBoolean();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setEnableFlagBoolean((Boolean)value);
            }
        }
        ,
        COARulesLOV1 {
            public Object get(COASearchVORowImpl obj) {
                return obj.getCOARulesLOV1();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COASegmentDefinitionsVO1 {
            public Object get(COASearchVORowImpl obj) {
                return obj.getCOASegmentDefinitionsVO1();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        COASourceSystemLOVVO1 {
            public Object get(COASearchVORowImpl obj) {
                return obj.getCOASourceSystemLOVVO1();
            }

            public void put(COASearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(COASearchVORowImpl object);

        public abstract void put(COASearchVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SOURCEVALUE = AttributesEnum.SourceValue.index();
    public static final int VALUEID = AttributesEnum.ValueId.index();
    public static final int TARGETVALUE = AttributesEnum.TargetValue.index();
    public static final int ENABLEDFLAG = AttributesEnum.EnabledFlag.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int RULENAME = AttributesEnum.RuleName.index();
    public static final int SOURCESYSTEM = AttributesEnum.SourceSystem.index();
    public static final int TARGETSYSTEM = AttributesEnum.TargetSystem.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int RULEID = AttributesEnum.RuleId.index();
    public static final int RULEID1 = AttributesEnum.RuleId1.index();
    public static final int RULEID2 = AttributesEnum.RuleId2.index();
    public static final int SOURCESEGMENT = AttributesEnum.SourceSegment.index();
    public static final int TARGETSEGMENT = AttributesEnum.TargetSegment.index();
    public static final int ENABLEFLAGBOOLEAN = AttributesEnum.EnableFlagBoolean.index();
    public static final int COARULESLOV1 = AttributesEnum.COARulesLOV1.index();
    public static final int COASEGMENTDEFINITIONSVO1 = AttributesEnum.COASegmentDefinitionsVO1.index();
    public static final int COASOURCESYSTEMLOVVO1 = AttributesEnum.COASourceSystemLOVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public COASearchVORowImpl() {
    }


    /**
     * Gets COASegmentValuesEO entity object.
     * @return the COASegmentValuesEO
     */
    public EntityImpl getCOASegmentValuesEO() {
        return (EntityImpl)getEntity(2);
    }


    /**
     * Gets COAMappingRulesEO entity object.
     * @return the COAMappingRulesEO
     */
    public EntityImpl getCOAMappingRulesEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets COASegmentsViewMappingEO entity object.
     * @return the COASegmentsViewMappingEO
     */
    public EntityImpl getCOASegmentsViewMappingEO() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for SOURCE_VALUE using the alias name SourceValue.
     * @return the SOURCE_VALUE
     */
    public String getSourceValue() {
        return (String) getAttributeInternal(SOURCEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_VALUE using the alias name SourceValue.
     * @param value value to set the SOURCE_VALUE
     */
    public void setSourceValue(String value) {
        setAttributeInternal(SOURCEVALUE, value);
    }

    /**
     * Gets the attribute value for VALUE_ID using the alias name ValueId.
     * @return the VALUE_ID
     */
    public Number getValueId() {
        return (Number) getAttributeInternal(VALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE_ID using the alias name ValueId.
     * @param value value to set the VALUE_ID
     */
    public void setValueId(Number value) {
        setAttributeInternal(VALUEID, value);
    }

    /**
     * Gets the attribute value for TARGET_VALUE using the alias name TargetValue.
     * @return the TARGET_VALUE
     */
    public String getTargetValue() {
        return (String) getAttributeInternal(TARGETVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_VALUE using the alias name TargetValue.
     * @param value value to set the TARGET_VALUE
     */
    public void setTargetValue(String value) {
        setAttributeInternal(TARGETVALUE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }


    /**
     * Gets the attribute value for RULE_ID using the alias name RuleId.
     * @return the RULE_ID
     */
    public Number getRuleId() {
        return (Number) getAttributeInternal(RULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ID using the alias name RuleId.
     * @param value value to set the RULE_ID
     */
    public void setRuleId(Number value) {
        setAttributeInternal(RULEID, value);
    }

    /**
     * Gets the attribute value for RULE_ID using the alias name RuleId1.
     * @return the RULE_ID
     */
    public Number getRuleId1() {
        return (Number) getAttributeInternal(RULEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ID using the alias name RuleId1.
     * @param value value to set the RULE_ID
     */
    public void setRuleId1(Number value) {
        setAttributeInternal(RULEID1, value);
    }

    /**
     * Gets the attribute value for RULE_ID using the alias name RuleId2.
     * @return the RULE_ID
     */
    public BigDecimal getRuleId2() {
        return (BigDecimal) getAttributeInternal(RULEID2);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ID using the alias name RuleId2.
     * @param value value to set the RULE_ID
     */
    public void setRuleId2(BigDecimal value) {
        setAttributeInternal(RULEID2, value);
    }

    /**
     * Gets the attribute value for SOURCE_SEGMENT using the alias name SourceSegment.
     * @return the SOURCE_SEGMENT
     */
    public String getSourceSegment() {
        return (String) getAttributeInternal(SOURCESEGMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_SEGMENT using the alias name SourceSegment.
     * @param value value to set the SOURCE_SEGMENT
     */
    public void setSourceSegment(String value) {
        setAttributeInternal(SOURCESEGMENT, value);
    }

    /**
     * Gets the attribute value for TARGET_SEGMENT using the alias name TargetSegment.
     * @return the TARGET_SEGMENT
     */
    public String getTargetSegment() {
        return (String) getAttributeInternal(TARGETSEGMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_SEGMENT using the alias name TargetSegment.
     * @param value value to set the TARGET_SEGMENT
     */
    public void setTargetSegment(String value) {
        setAttributeInternal(TARGETSEGMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EnableFlagBoolean.
     * @return the EnableFlagBoolean
     */
    public Boolean getEnableFlagBoolean() {
        //return (Boolean) getAttributeInternal(ENABLEFLAGBOOLEAN);
        if (this.getEnabledFlag() != null && 
            this.getEnabledFlag().equalsIgnoreCase("Y")){
            return true;
        }
        return false;

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EnableFlagBoolean.
     * @param value value to set the  EnableFlagBoolean
     */
    public void setEnableFlagBoolean(Boolean value) {
        
        if (value){
            this.setEnabledFlag("Y");
        }
        else{
            this.setEnabledFlag("N");
        }
        setAttributeInternal(ENABLEFLAGBOOLEAN, value);
    }

    /**
     * Gets the attribute value for RULE_NAME using the alias name RuleName.
     * @return the RULE_NAME
     */
    public String getRuleName() {
        return (String) getAttributeInternal(RULENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_NAME using the alias name RuleName.
     * @param value value to set the RULE_NAME
     */
    public void setRuleName(String value) {
        setAttributeInternal(RULENAME, value);
    }

    /**
     * Gets the attribute value for SOURCE_SYSTEM using the alias name SourceSystem.
     * @return the SOURCE_SYSTEM
     */
    public String getSourceSystem() {
        return (String) getAttributeInternal(SOURCESYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_SYSTEM using the alias name SourceSystem.
     * @param value value to set the SOURCE_SYSTEM
     */
    public void setSourceSystem(String value) {
        setAttributeInternal(SOURCESYSTEM, value);
    }

    /**
     * Gets the attribute value for TARGET_SYSTEM using the alias name TargetSystem.
     * @return the TARGET_SYSTEM
     */
    public String getTargetSystem() {
        return (String) getAttributeInternal(TARGETSYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_SYSTEM using the alias name TargetSystem.
     * @param value value to set the TARGET_SYSTEM
     */
    public void setTargetSystem(String value) {
        setAttributeInternal(TARGETSYSTEM, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ENABLED_FLAG using the alias name EnabledFlag.
     * @return the ENABLED_FLAG
     */
    public String getEnabledFlag() {
        return (String) getAttributeInternal(ENABLEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ENABLED_FLAG using the alias name EnabledFlag.
     * @param value value to set the ENABLED_FLAG
     */
    public void setEnabledFlag(String value) {
        setAttributeInternal(ENABLEDFLAG, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> COARulesLOV1.
     */
    public RowSet getCOARulesLOV1() {
        return (RowSet)getAttributeInternal(COARULESLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COASegmentDefinitionsVO1.
     */
    public RowSet getCOASegmentDefinitionsVO1() {
        return (RowSet)getAttributeInternal(COASEGMENTDEFINITIONSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COASourceSystemLOVVO1.
     */
    public RowSet getCOASourceSystemLOVVO1() {
        return (RowSet)getAttributeInternal(COASOURCESYSTEMLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
