package deloitte.fin.gl.coa.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 00:35:54 IST 2016
// ---------------------------------------------------------------------
public interface COAAM extends ApplicationModule {
    void findCOAValues(String sourceSystem, String targetSystem,
                       String mappingRule, String sourceSegment,
                       String targetSegemnt, String sourceValue,
                       String targetValue);

    String getCOASegments(String sourceSystem, String targetSystem,
                          String sourceString);
}
