package deloitte.fin.gl.coa.module.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 00:35:54 IST 2016
// ---------------------------------------------------------------------
public interface COAAM extends ApplicationModule {
    void findCOAValues(String sourceSystem, String targetSystem,
                       String mappingRule, String sourceSegment,
                       String targetSegemnt, String sourceValue,
                       String targetValue);

    String getCOASegments(String sourceSystem, String targetSystem,
                          String sourceString);

    void callCOACreatingMappingRuleProc(String sourceSystemStr,
                                        String targetSystemStr,
                                        String ruleNameStr, String descStr,
                                        String seqStr, Number[] sourceSegArray,
                                        Number[] targetSeqArray);

    void executeCOAMappingRuleVO(String ruleStr, String descStr, String seqStr,
                                 String sourceStr, String destStr);

    void findSystemValues(String systemName);

    void selectSystemValues(String systemName);
}
