package deloitte.fin.gl.coa.module.client;

import deloitte.fin.gl.coa.module.common.COAAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 00:35:54 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class COAAMClient extends ApplicationModuleImpl implements COAAM {
    /**
     * This is the default constructor (do not remove).
     */
    public COAAMClient() {
    }

    public void findCOAValues(String sourceSystem, String targetSystem,
                              String mappingRule, String sourceSegment,
                              String targetSegemnt, String sourceValue,
                              String targetValue) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findCOAValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {sourceSystem, targetSystem, mappingRule, sourceSegment, targetSegemnt, sourceValue, targetValue});
        return;
    }

    public String getCOASegments(String sourceSystem, String targetSystem,
                                 String sourceString) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCOASegments",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {sourceSystem, targetSystem, sourceString});
        return (String)_ret;
    }
}
