package deloitte.fin.gl.coa.module.server.serviceinterface;

import deloitte.fin.gl.coa.module.COAAMImpl;
import deloitte.fin.gl.coa.module.common.serviceinterface.COAAMService;

import java.lang.reflect.Method;

import java.util.HashMap;
import java.util.Map;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 12:52:35 IST 2016
// ---------------------------------------------------------------------
@Interceptors( { ServiceContextInterceptor.class })
@Stateless(name="deloitte.fin.gl.coa.module.common.COAAMServiceBean",
    mappedName="COAAMServiceBean")
@Remote(COAAMService.class)
@PortableWebService(targetNamespace="/deloitte/fin/gl/coa/module/common/",
    serviceName="COAAMService", portName="COAAMServiceSoapHttpPort",
    endpointInterface="deloitte.fin.gl.coa.module.common.serviceinterface.COAAMService")
public class COAAMServiceImpl extends ServiceImpl implements COAAMService {
    private static boolean _isInited = false;

    private static final Map _map = new HashMap();

    /**
     * This is the default constructor (do not remove).
     */
    public COAAMServiceImpl() {
        init();
        setApplicationModuleDefName("deloitte.fin.gl.coa.module.COAAM");
        setConfigurationName("COAAMService");
    }


    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (COAAMServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("deloitte/fin/gl/coa/module/common/serviceinterface/", "COAAMService.xsd");
                _map.put("getTargetString",
                         COAAMImpl.class.getMethod("getTargetString",
                                                   new Class[] { String.class,
                                                                 String.class,
                                                                 String.class }));
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }


    /**
     * getTargetString: generated method. Do not modify.
     */
    public String getTargetString(String pSourceSystem, String pTargetSystem,
                                  String pSourceString) throws ServiceException {
        return (String)invokeCustom((Method)_map.get("getTargetString"),
                                    new Object[] { pSourceSystem,
                                                   pTargetSystem,
                                                   pSourceString },
                                    new String[] { null, null, null }, false);
    }
}
